//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.ItemUsedStocks = new HashSet<ItemUsedStock>();
            this.OrderDetailMasters = new HashSet<OrderDetailMaster>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
        }
    
        public int ItemMaster_ID { get; set; }
        public Nullable<int> ItemCategory_ID { get; set; }
        public string ItemName { get; set; }
        public Nullable<bool> IsVeg { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<int> ReOrderLevel { get; set; }
        public Nullable<int> MinimumQuantatity { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ICollection<ItemUsedStock> ItemUsedStocks { get; set; }
        public virtual ICollection<OrderDetailMaster> OrderDetailMasters { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
    }
}
