//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        public ItemCategory()
        {
            this.ItemMasters = new HashSet<ItemMaster>();
        }
    
        public int ItemCategory_ID { get; set; }
        public string ItemCategoryName { get; set; }
        public Nullable<bool> IsMenuItem { get; set; }
        public Nullable<bool> IsAssets { get; set; }
        public Nullable<bool> IsService { get; set; }
        public Nullable<bool> IsRawMetirial { get; set; }
    
        public virtual ICollection<ItemMaster> ItemMasters { get; set; }
    }
}
