//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Paymnet_Id { get; set; }
        public Nullable<int> OrderMaster_Id { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> PayementDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
    }
}
