//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturnDetail
    {
        public int PurchaseReturnDetail_ID { get; set; }
        public Nullable<int> PurchaseReturn_ID { get; set; }
        public Nullable<int> ItemMaster_ID { get; set; }
        public Nullable<int> Quatntity { get; set; }
        public string Remarks { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual PurchaseReturn PurchaseReturn { get; set; }
    }
}
