//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
        }
    
        public int Purchase_ID { get; set; }
        public Nullable<int> Vendor_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BillNo { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
    }
}
