//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMaster
    {
        public TableMaster()
        {
            this.OrderMasters = new HashSet<OrderMaster>();
        }
    
        public int Table_ID { get; set; }
        public Nullable<int> Floor_ID { get; set; }
        public Nullable<int> TableType_ID { get; set; }
        public Nullable<int> TableCapacity { get; set; }
        public string TableNo { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
        public virtual TableType TableType { get; set; }
    }
}
