//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int Vendor_ID { get; set; }
        public string VendorName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string GstNo { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
