//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaffronHotelAdminManagement_MVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaiterMaster
    {
        public WaiterMaster()
        {
            this.OrderMasters = new HashSet<OrderMaster>();
            this.WaiterAttendences = new HashSet<WaiterAttendence>();
        }
    
        public int WaiterMaster_Id { get; set; }
        public string WaiterName { get; set; }
        public string ContctNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string AdharCardNo { get; set; }
    
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
        public virtual ICollection<WaiterAttendence> WaiterAttendences { get; set; }
    }
}
